[2024-02-22 19:53:48,447][0][INFO][color_logger.py:203] Logfile: /data1/xiayuyang/online_mcmt/logs/0_2024-02-22-19-53-48-446110.log
[2024-02-22 19:53:48,678][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:48,906][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:49,161][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:49,377][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:49,597][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:49,816][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:50,012][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:50,240][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:50,447][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:50,672][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:50,890][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:51,093][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:51,314][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:51,513][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:51,740][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:51,965][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:52,175][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:52,401][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:52,616][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:52,858][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:53,082][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:53,312][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:53,516][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:53,747][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:53,981][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:54,192][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:54,396][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:54,642][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:54,872][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:55,088][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:55,310][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:55,550][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:55,765][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:55,991][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:56,204][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:56,452][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:56,693][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:56,915][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:57,141][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:57,369][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:57,592][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:57,838][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:58,079][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:58,315][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:58,545][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:58,761][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:58,966][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:59,201][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:59,435][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:59,652][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:53:59,881][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:00,142][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:00,428][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:00,674][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:00,903][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:01,124][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:01,339][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:01,546][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:01,749][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:01,964][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:02,164][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:02,358][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:02,553][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:02,769][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:02,808][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:02,809][0][INFO][generic_smbo.py:295] Iter 1, objectives: [inf, inf].
[2024-02-22 19:54:02,810][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:02,810][0][INFO][generic_smbo.py:295] Iter 2, objectives: [inf, inf].
[2024-02-22 19:54:02,811][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:02,811][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:02,812][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:54:02,812][0][INFO][generic_smbo.py:295] Iter 3, objectives: [inf, inf].
[2024-02-22 19:54:02,812][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:02,813][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:02,813][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:54:02,814][0][INFO][generic_smbo.py:295] Iter 4, objectives: [inf, inf].
[2024-02-22 19:54:02,814][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:02,815][0][INFO][generic_smbo.py:295] Iter 5, objectives: [inf, inf].
[2024-02-22 19:54:02,815][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:02,816][0][INFO][generic_smbo.py:295] Iter 6, objectives: [inf, inf].
[2024-02-22 19:54:02,816][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:02,817][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:02,817][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:54:02,818][0][INFO][generic_smbo.py:295] Iter 7, objectives: [inf, inf].
[2024-02-22 19:54:02,818][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:02,819][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:02,819][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:54:02,820][0][INFO][generic_smbo.py:295] Iter 8, objectives: [inf, inf].
[2024-02-22 19:54:02,820][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:02,821][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:02,821][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:54:02,821][0][INFO][generic_smbo.py:295] Iter 9, objectives: [inf, inf].
[2024-02-22 19:54:02,823][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,824][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:54:02,825][0][INFO][generic_smbo.py:295] Iter 10, objectives: [inf, inf].
[2024-02-22 19:54:02,825][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,827][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:02,827][0][INFO][generic_smbo.py:295] Iter 11, objectives: [inf, inf].
[2024-02-22 19:54:02,828][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,829][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:02,829][0][INFO][generic_smbo.py:295] Iter 12, objectives: [inf, inf].
[2024-02-22 19:54:02,829][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-02-22 19:54:02,830][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:02,831][0][INFO][generic_smbo.py:295] Iter 13, objectives: [inf, inf].
[2024-02-22 19:54:02,831][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-02-22 19:54:02,832][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:54:02,832][0][INFO][generic_smbo.py:295] Iter 14, objectives: [inf, inf].
[2024-02-22 19:54:02,833][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,834][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:54:02,834][0][INFO][generic_smbo.py:295] Iter 15, objectives: [inf, inf].
[2024-02-22 19:54:02,835][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,836][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:02,837][0][INFO][generic_smbo.py:295] Iter 16, objectives: [inf, inf].
[2024-02-22 19:54:02,837][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-02-22 19:54:02,838][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:02,838][0][INFO][generic_smbo.py:295] Iter 17, objectives: [inf, inf].
[2024-02-22 19:54:02,839][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,840][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:54:02,840][0][INFO][generic_smbo.py:295] Iter 18, objectives: [inf, inf].
[2024-02-22 19:54:02,841][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-02-22 19:54:02,842][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:02,842][0][INFO][generic_smbo.py:295] Iter 19, objectives: [inf, inf].
[2024-02-22 19:54:02,842][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,843][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:02,844][0][INFO][generic_smbo.py:295] Iter 20, objectives: [inf, inf].
[2024-02-22 19:54:02,844][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,845][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:02,846][0][INFO][generic_smbo.py:295] Iter 21, objectives: [inf, inf].
[2024-02-22 19:54:02,846][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,847][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:02,848][0][INFO][generic_smbo.py:295] Iter 22, objectives: [inf, inf].
[2024-02-22 19:54:02,848][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,849][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:02,850][0][INFO][generic_smbo.py:295] Iter 23, objectives: [inf, inf].
[2024-02-22 19:54:02,850][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,851][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:54:02,852][0][INFO][generic_smbo.py:295] Iter 24, objectives: [inf, inf].
[2024-02-22 19:54:02,852][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,853][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:54:02,854][0][INFO][generic_smbo.py:295] Iter 25, objectives: [inf, inf].
[2024-02-22 19:54:02,854][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,855][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:02,856][0][INFO][generic_smbo.py:295] Iter 26, objectives: [inf, inf].
[2024-02-22 19:54:02,856][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,858][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:54:02,858][0][INFO][generic_smbo.py:295] Iter 27, objectives: [inf, inf].
[2024-02-22 19:54:02,859][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,860][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:02,861][0][INFO][generic_smbo.py:295] Iter 28, objectives: [inf, inf].
[2024-02-22 19:54:02,861][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,862][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:02,863][0][INFO][generic_smbo.py:295] Iter 29, objectives: [inf, inf].
[2024-02-22 19:54:02,863][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,865][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:54:02,865][0][INFO][generic_smbo.py:295] Iter 30, objectives: [inf, inf].
[2024-02-22 19:54:02,866][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,867][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:54:02,868][0][INFO][generic_smbo.py:295] Iter 31, objectives: [inf, inf].
[2024-02-22 19:54:02,868][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,869][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:02,869][0][INFO][generic_smbo.py:295] Iter 32, objectives: [inf, inf].
[2024-02-22 19:54:02,870][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-02-22 19:54:02,873][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:02,873][0][INFO][generic_smbo.py:295] Iter 33, objectives: [inf, inf].
[2024-02-22 19:54:02,874][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,875][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:54:02,876][0][INFO][generic_smbo.py:295] Iter 34, objectives: [inf, inf].
[2024-02-22 19:54:02,876][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,879][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:02,879][0][INFO][generic_smbo.py:295] Iter 35, objectives: [inf, inf].
[2024-02-22 19:54:02,880][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,882][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:02,882][0][INFO][generic_smbo.py:295] Iter 36, objectives: [inf, inf].
[2024-02-22 19:54:02,883][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,887][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:02,887][0][INFO][generic_smbo.py:295] Iter 37, objectives: [inf, inf].
[2024-02-22 19:54:02,888][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,892][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:02,892][0][INFO][generic_smbo.py:295] Iter 38, objectives: [inf, inf].
[2024-02-22 19:54:02,892][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-02-22 19:54:02,895][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:54:02,895][0][INFO][generic_smbo.py:295] Iter 39, objectives: [inf, inf].
[2024-02-22 19:54:02,896][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,899][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:54:02,899][0][INFO][generic_smbo.py:295] Iter 40, objectives: [inf, inf].
[2024-02-22 19:54:02,900][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:02,904][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:02,904][0][INFO][generic_smbo.py:295] Iter 41, objectives: [inf, inf].
[2024-02-22 19:54:02,905][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:03,126][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:03,126][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:03,127][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-02-22 19:54:03,127][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:54:03,127][0][INFO][generic_smbo.py:295] Iter 42, objectives: [inf, inf].
[2024-02-22 19:54:03,128][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:03,324][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:03,325][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:54:03,326][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:54:03,326][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:54:03,326][0][INFO][generic_smbo.py:295] Iter 43, objectives: [inf, inf].
[2024-02-22 19:54:03,327][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:03,524][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:03,524][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:54:03,525][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:54:03,526][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:54:03,526][0][INFO][generic_smbo.py:295] Iter 44, objectives: [inf, inf].
[2024-02-22 19:54:03,527][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:03,751][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:03,752][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:03,752][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:03,753][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:54:03,753][0][INFO][generic_smbo.py:295] Iter 45, objectives: [inf, inf].
[2024-02-22 19:54:03,754][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:03,979][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:03,980][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:03,981][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:03,981][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:54:03,981][0][INFO][generic_smbo.py:295] Iter 46, objectives: [inf, inf].
[2024-02-22 19:54:03,982][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:04,223][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:04,223][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:04,224][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:04,225][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:54:04,225][0][INFO][generic_smbo.py:295] Iter 47, objectives: [inf, inf].
[2024-02-22 19:54:04,226][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:04,455][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:04,456][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:54:04,456][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-22 19:54:04,457][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:54:04,457][0][INFO][generic_smbo.py:295] Iter 48, objectives: [inf, inf].
[2024-02-22 19:54:04,458][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:04,683][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:04,684][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:04,684][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:04,685][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:54:04,685][0][INFO][generic_smbo.py:295] Iter 49, objectives: [inf, inf].
[2024-02-22 19:54:04,686][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-22 19:54:04,907][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-22 19:54:04,907][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:04,908][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 790, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
NameError: name 'lazy_threshold_' is not defined

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-22 19:54:04,908][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-22 19:54:04,908][0][INFO][generic_smbo.py:295] Iter 50, objectives: [inf, inf].
[2024-02-22 19:54:04,924][0][WARNING][history.py:651] No feasible observations! Return empty pareto.
