[2024-01-25 00:27:51,803][0][INFO][color_logger.py:203] Logfile: /data1/xiayuyang/online_mcmt/logs/0_2024-01-25-00-27-51-802722.log
[2024-01-25 01:05:07,309][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-25 01:05:07,310][0][INFO][generic_smbo.py:295] Iter 1, objectives: [inf, inf].
[2024-01-25 01:18:27,416][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'fps_camera3': '4',
  'fps_camera4': '10',
  'fps_camera5': '10',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-25 01:18:27,417][0][INFO][generic_smbo.py:295] Iter 2, objectives: [inf, inf].
[2024-01-25 01:59:06,322][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '1',
  'fps_camera5': '4',
  'lazy_threshold': 0.76,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-25 01:59:06,323][0][INFO][generic_smbo.py:295] Iter 3, objectives: [inf, inf].
[2024-01-25 02:37:26,269][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-25 02:37:26,275][0][INFO][generic_smbo.py:295] Iter 4, objectives: [inf, inf].
[2024-01-25 02:51:22,940][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '10',
  'fps_camera5': '10',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-25 02:51:22,941][0][INFO][generic_smbo.py:295] Iter 5, objectives: [inf, inf].
[2024-01-25 03:33:25,894][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.84,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-25 03:33:25,895][0][INFO][generic_smbo.py:295] Iter 6, objectives: [inf, inf].
[2024-01-25 03:58:08,682][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.74,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-25 03:58:08,683][0][INFO][generic_smbo.py:295] Iter 7, objectives: [inf, inf].
[2024-01-25 04:44:26,665][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.6,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-25 04:44:26,665][0][INFO][generic_smbo.py:295] Iter 8, objectives: [inf, inf].
[2024-01-25 05:25:25,633][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '1',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-25 05:25:25,639][0][INFO][generic_smbo.py:295] Iter 9, objectives: [inf, inf].
[2024-01-25 05:25:25,643][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-25 06:04:33,346][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '2',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '1',
  'lazy_threshold': 0.76,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-25 06:04:33,347][0][INFO][generic_smbo.py:295] Iter 10, objectives: [inf, inf].
[2024-01-25 06:04:33,362][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 07:15:18,425][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '2',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-25 07:15:18,426][0][INFO][generic_smbo.py:295] Iter 11, objectives: [inf, inf].
[2024-01-25 07:15:18,428][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 07:39:43,495][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '2',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-25 07:39:43,495][0][INFO][generic_smbo.py:295] Iter 12, objectives: [inf, inf].
[2024-01-25 07:39:43,496][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 08:11:14,369][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '4',
  'fps_camera5': '4',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-25 08:11:14,370][0][INFO][generic_smbo.py:295] Iter 13, objectives: [inf, inf].
[2024-01-25 08:11:14,371][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 08:46:10,847][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.8999999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-25 08:46:10,848][0][INFO][generic_smbo.py:295] Iter 14, objectives: [inf, inf].
[2024-01-25 08:46:10,849][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 09:13:03,299][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-25 09:13:03,301][0][INFO][generic_smbo.py:295] Iter 15, objectives: [inf, inf].
[2024-01-25 09:13:03,303][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 09:41:18,982][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '4',
  'lazy_threshold': 0.64,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-25 09:41:18,983][0][INFO][generic_smbo.py:295] Iter 16, objectives: [inf, inf].
[2024-01-25 09:41:18,984][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 10:10:36,078][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    f1_score_all = 0
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-25 10:10:36,078][0][INFO][generic_smbo.py:295] Iter 17, objectives: [inf, inf].
[2024-01-25 10:10:36,080][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 10:46:08,912][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    for cam in cams:
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '2',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.88,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-25 10:46:08,912][0][INFO][generic_smbo.py:295] Iter 18, objectives: [inf, inf].
[2024-01-25 10:46:08,913][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 11:20:24,569][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    for cam in cams:
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    if (total_iou / frame_cnt) > avg_iou:
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.6799999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-25 11:20:24,570][0][INFO][generic_smbo.py:295] Iter 19, objectives: [inf, inf].
[2024-01-25 11:20:24,573][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 12:04:19,930][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    recall_all = 0
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    frame_cnt += 1
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '1',
  'lazy_threshold': 0.62,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-25 12:04:19,932][0][INFO][generic_smbo.py:295] Iter 20, objectives: [inf, inf].
[2024-01-25 12:04:19,935][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 12:35:22,533][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    f1_score_all = 0
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    elif (i in f_list2):
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.86,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-25 12:35:22,533][0][INFO][generic_smbo.py:295] Iter 21, objectives: [inf, inf].
[2024-01-25 12:35:22,534][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-25 12:59:42,096][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    cams = os.listdir(cams_dir_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    elif (i in f_list2):
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-25 12:59:42,097][0][INFO][generic_smbo.py:295] Iter 22, objectives: [inf, inf].
[2024-01-25 12:59:42,098][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-25 13:30:52,199][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    cams = os.listdir(cams_dir_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    elif (i in f_list2):
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-25 13:30:52,199][0][INFO][generic_smbo.py:295] Iter 23, objectives: [inf, inf].
[2024-01-25 13:30:52,201][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 13:56:23,743][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    cams = os.listdir(cams_dir_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    elif (i in f_list2):
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '4',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-25 13:56:23,744][0][INFO][generic_smbo.py:295] Iter 24, objectives: [inf, inf].
[2024-01-25 13:56:23,745][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 14:08:28,506][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    cams = os.listdir(cams_dir_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    elif (i in f_list2):
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '2',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-25 14:08:28,511][0][INFO][generic_smbo.py:295] Iter 25, objectives: [inf, inf].
[2024-01-25 14:08:28,516][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 14:25:32,633][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    cams = os.listdir(cams_dir_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    elif (i in f_list2):
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '2',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '2',
  'lazy_threshold': 0.74,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-25 14:25:32,634][0][INFO][generic_smbo.py:295] Iter 26, objectives: [inf, inf].
[2024-01-25 14:25:32,636][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 15:09:43,997][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    camera_num = len(cams)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    elif (i in f_list2):
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.64,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-25 15:09:43,998][0][INFO][generic_smbo.py:295] Iter 27, objectives: [inf, inf].
[2024-01-25 15:09:43,999][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 15:58:54,105][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    gt_bboxes = [item[1:] for item in gt]
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    skip_frame += 1
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '1',
  'fps_camera5': '2',
  'lazy_threshold': 0.74,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-25 15:58:54,106][0][INFO][generic_smbo.py:295] Iter 28, objectives: [inf, inf].
[2024-01-25 15:58:54,107][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 16:54:59,540][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    gt_bboxes = [item[1:] for item in gt]
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    skip_frame += 1
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.8999999999999999,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-25 16:54:59,549][0][INFO][generic_smbo.py:295] Iter 29, objectives: [inf, inf].
[2024-01-25 16:54:59,550][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 17:26:10,457][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    gt_bboxes = [item[1:] for item in gt]
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    skip_frame += 1
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '4',
  'fps_camera3': '4',
  'fps_camera4': '1',
  'fps_camera5': '2',
  'lazy_threshold': 0.6,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-25 17:26:10,458][0][INFO][generic_smbo.py:295] Iter 30, objectives: [inf, inf].
[2024-01-25 17:26:10,459][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 17:52:03,084][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    gt_bboxes = [item[1:] for item in gt]
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    skip_frame += 1
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '4',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.76,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-25 17:52:03,085][0][INFO][generic_smbo.py:295] Iter 31, objectives: [inf, inf].
[2024-01-25 17:52:03,086][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-25 18:15:20,122][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 935, in profile
    gt_bboxes = [item[1:] for item in gt]
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 386, in mot_metrics
    skip_frame += 1
ZeroDivisionError: division by zero

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '2',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.86,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-25 18:15:20,123][0][INFO][generic_smbo.py:295] Iter 32, objectives: [inf, inf].
[2024-01-25 18:15:20,124][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
